name: Auto Rebase X11

on:
  push:
    branches:
      - main
jobs:
  rebase-wzkj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Auto Rebase wzkj
        uses: dearfl/rebase@v1
        with:
          branch: wzkj

  rebase-wzkj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Auto Rebase x11
        uses: dearfl/rebase@v1
        with:
          base: wzkj
          branch: x11
