name: Auto Rebase X11

on:
  push:
    branches:
      - main
jobs:
  rebase-x11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Auto Rebase X11
        uses: dearfl/rebase@v1
        with:
          branch: x11

  rebase-wzkj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Auto Rebase wzkj
        uses: dearfl/rebase@v1
        with:
          base: x11
          branch: wzkj
